### PR TITLE
Seandon dev

### PR DESCRIPTION
**Pull request by erulabs**
1. Improve application-node stencil with PM2 fixes and removes dep on 'application' cookbook in favor of 'deploy' resource

2. Add GlusterFS stencil

3. Improve rackspace_networks to improve handling one-box-wonders (include self in the scan for other servers, essentially favors using a servers own servicenet or cloudnetwork address rather than 127.0.0.1 on first chef-client run).

Since no one is using any of this yet, I'm just cramming stuff into my branch.

If someone wants, I can clean this PR up, but I recommend a merge-first-purge-later approach, at least until we have people using this :) ;)

Thanks!

### CODE REVIEW

**Comment by asdqwex** [comment]
:+1: Looks good, a simple starting point.

**Comment by martinb3** [comment]
I think it's an industry best practice to only merge code we'd actually use or want to deploy to master. Many of the DevOps Conference Talks and Keynotes all point out that you should always keep `master` something you'd actually use, and never to push code to master that you might not use or that violates your own best practices, as it's so hard to back out from that.

Some interesting blog posts & discussion threads about it:
[Zero Downtime Deployment and Deployment Pipelines](http://blog.codeship.com/zero-downtime-deployment/)
[Should every git commit leave the project in a working state?](http://programmers.stackexchange.com/questions/109107/should-every-git-commit-leave-the-project-in-a-working-state)
[Is it ever OK to commit non-working code?](http://programmers.stackexchange.com/questions/211608/is-it-ever-ok-to-commit-non-working-code)

I'd suggest we keep the code in this PR in a feature branch, and we shouldn't ever let lines like the following get into master, since we settled on standards that these lines go against (these lines are from the commits in this PR):

```
# Sorry, we don't support centos just yet. Stay tuned!
```
```
package 'build-essential'
```

Unless we're deploying customers using this code, I don't see any urgency in merging this to master, as it could actually create more unique migrations from this code to the final design (would make our work even more difficult once we have stencils we all agree on).

/CC @brint @jujugrrr for their thoughts.

**Comment by jujugrrr** [comment]
> Unless we're deploying customers using this code, I don't see any urgency in merging this to master, as it could actually create more unique migrations from this code to the final design (would make our work even more difficult once we have stencils we all agree on).

I do agree. I think the PR should be cleaned, reviewed and only merged if it passes requirements. By example I'm not sure why we are removing nginx from the stencil. 
I thought we were having tests for stencils, will this PR break any previous features?

**Comment by erulabs** [comment]
>Unless we're deploying customers using this code

Be more disconnected, I dare you.

This code is production on 6 major customers.

**Comment by erulabs** [comment]
Closing PR as merging is obviously not possible in a reasonable amount of time and reviews by other authors / users are wholly ignored.

Will continue building out of my own stencil repo until which time managers get me into a meeting and force someone to merge this :)

Thanks!

**Pull request closed without merging**
